name: "Setup Python"
description: "Setup Python"
inputs:
  python-version:
    description: "Python Version"
    required: true
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}