name: Data Ingestion Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Daily at 1 AM UTC

jobs:
  download:
    if: >
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'schedule' && github.ref == 'refs/heads/main')
    name: Download FX and Stock Tickers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine

      - name: Build Package
        run: python -m build

      - name: Install Package
        run: pip install dist/*.whl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-1
          role-session-name: GitHubActionsSession

      - name: Run Downloader
        run: |
          python scripts/downloader.py

      - name: Cache "downloads"
        if: always()
        uses: actions/cache@v4
        with:
          path: downloads
          key: downloads-${{ github.run_id }}
          restore-keys: |
            downloads-
