name: "Install Package"
description: "Install Ingestion Package"

inputs:
  run-id:
    description: "GitHub Run ID (used for caching)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore "dist" Cache
      uses: actions/cache@v4
      with:
        path: dist
        key: dist-${{ inputs.run-id }}

    - name: Install Package
      run: |
        pip install dist/*.whl
      shell: bash